import dotenv from "dotenv";
import { z } from "zod";

dotenv.config();

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  PORT: z.coerce.number().default(8080),
  APP_NAME: z.string().default("VEDAAPEX"),
  APP_BASE_URL: z.string().url().default("http://localhost:8080"),
  API_PREFIX: z.string().default("/api"),
  API_VERSION: z.string().default("v1"),
  DATABASE_URL: z.string().min(1),
  REDIS_URL: z.string().min(1),
  JWT_ACCESS_SECRET: z.string().min(16),
  JWT_REFRESH_SECRET: z.string().min(16),
  JWT_ACCESS_TTL: z.string().default("15m"),
  JWT_REFRESH_TTL: z.string().default("30d"),
  JWT_ISSUER: z.string().default("vedaapex"),
  JWT_AUDIENCE: z.string().default("vedaapex-users"),
  SESSION_COOKIE_NAME: z.string().default("vedaapex.sid"),
  ALLOWED_ORIGINS: z.string().default("http://localhost:3000"),
  CORS_ALLOW_CREDENTIALS: z.coerce.boolean().default(true),
  ENABLE_SWAGGER: z.coerce.boolean().default(true),
  ENABLE_CSRF: z.coerce.boolean().default(false),
  ENABLE_INLINE_QUEUE_WORKERS: z.coerce.boolean().default(true),
  GOOGLE_CLIENT_ID: z.string().optional(),
  GOOGLE_CLIENT_SECRET: z.string().optional(),
  FIREBASE_PROJECT_ID: z.string().optional(),
  FIREBASE_SERVICE_ACCOUNT_JSON: z.string().optional(),
  FIREBASE_CLIENT_EMAIL: z.string().optional(),
  FIREBASE_PRIVATE_KEY: z.string().optional(),
  FIREBASE_STORAGE_BUCKET: z.string().optional(),
  FIREBASE_WEB_API_KEY: z.string().optional(),
  FIREBASE_AUTH_DOMAIN: z.string().optional(),
  FIREBASE_MESSAGING_SENDER_ID: z.string().optional(),
  FIREBASE_APP_ID: z.string().optional(),
  FIREBASE_MEASUREMENT_ID: z.string().optional(),
  STORAGE_PROVIDER: z.enum(["r2", "firebase"]).default("r2"),
  R2_ACCOUNT_ID: z.string().optional(),
  R2_ACCESS_KEY_ID: z.string().optional(),
  R2_SECRET_ACCESS_KEY: z.string().optional(),
  R2_BUCKET: z.string().optional(),
  R2_PUBLIC_BASE_URL: z.string().optional(),
  R2_ENDPOINT: z.string().optional(),
  SIGNED_URL_TTL_SECONDS: z.coerce.number().default(900),
  GROQ_API_KEY: z.string().optional(),
  GROQ_MODEL: z.string().default("llama-3.3-70b-versatile"),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_MODEL: z.string().default("gpt-4.1-mini"),
  GEMINI_API_KEY: z.string().optional(),
  GEMINI_MODEL: z.string().default("gemini-1.5-pro"),
  AI_PROVIDER_PRIORITY: z.string().default("groq,openai,gemini"),
  RAZORPAY_KEY_ID: z.string().optional(),
  RAZORPAY_KEY_SECRET: z.string().optional(),
  RAZORPAY_WEBHOOK_SECRET: z.string().optional(),
  RAZORPAY_CURRENCY: z.string().default("INR"),
  RAZORPAY_MIN_AMOUNT_PAISA: z.coerce.number().default(1000),
  MEDIA_PROCESSOR_MODE: z.enum(["passthrough", "http"]).default("passthrough"),
  MEDIA_PROCESSOR_BASE_URL: z.string().optional(),
  MEDIA_PROCESSOR_API_KEY: z.string().optional(),
  MEDIA_UPLOAD_MAX_MB: z.coerce.number().default(120),
  IMAGE_ALLOWED_MIME: z.string().default("image/png,image/jpeg,image/webp"),
  VIDEO_ALLOWED_MIME: z.string().default("video/mp4,video/quicktime,video/webm"),
  OTP_TTL_SECONDS: z.coerce.number().default(300),
  OTP_MAX_ATTEMPTS: z.coerce.number().default(5),
  OTP_MOCK_DELIVERY: z.coerce.boolean().default(true),
  OTP_DEV_BYPASS_CODE: z.string().default("123456"),
  EMAIL_FROM: z.string().default("no-reply@vedaapex.com"),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.coerce.number().default(587),
  SMTP_USER: z.string().optional(),
  SMTP_PASS: z.string().optional(),
  MAX_UPLOAD_MB: z.coerce.number().default(25),
  PDF_ALLOWED_MIME: z.string().default("application/pdf"),
  TRUST_PROXY: z.coerce.boolean().default(true),
  LOG_LEVEL: z.enum(["fatal", "error", "warn", "info", "debug", "trace", "silent"]).default("info"),
  RATE_LIMIT_WINDOW_MS: z.coerce.number().default(900000),
  RATE_LIMIT_MAX: z.coerce.number().default(250),
  AUTH_RATE_LIMIT_WINDOW_MS: z.coerce.number().default(900000),
  AUTH_RATE_LIMIT_MAX: z.coerce.number().default(25),
  ANALYTICS_RETENTION_DAYS: z.coerce.number().default(365),
});

const parsed = envSchema.safeParse(process.env);

if (!parsed.success) {
  throw new Error(`Invalid environment variables: ${parsed.error.flatten().fieldErrors}`);
}

export const env = {
  ...parsed.data,
  allowedOrigins: parsed.data.ALLOWED_ORIGINS.split(",").map((origin) => origin.trim()).filter(Boolean),
  aiProviderPriority: parsed.data.AI_PROVIDER_PRIORITY.split(",").map((provider) => provider.trim()).filter(Boolean),
  imageAllowedMime: parsed.data.IMAGE_ALLOWED_MIME.split(",").map((mime) => mime.trim()).filter(Boolean),
  videoAllowedMime: parsed.data.VIDEO_ALLOWED_MIME.split(",").map((mime) => mime.trim()).filter(Boolean),
};
