import edge_tts
import base64

class ApexSpeechProvider:
    @staticmethod
    async def run_model(text: str, voice: str = None) -> str:
        # Default to a highly realistic neural voice (Aria is extremely human-like)
        selected_voice = "en-US-AriaNeural"
        
        if voice:
            v_lower = voice.lower()
            if "male" in v_lower and "hindi" not in v_lower:
                selected_voice = "en-US-GuyNeural"
            elif "female" in v_lower and "hindi" not in v_lower:
                selected_voice = "en-US-JennyNeural"
            elif "hindi_male" in v_lower:
                selected_voice = "hi-IN-MadhurNeural"
            elif "hindi_female" in v_lower or "hindi" in v_lower:
                selected_voice = "hi-IN-SwaraNeural"
            else:
                # Direct voice identifier if they know edge-tts names
                selected_voice = voice

        try:
            communicate = edge_tts.Communicate(text, selected_voice)
            audio_bytes = b""
            async for chunk in communicate.stream():
                if chunk["type"] == "audio":
                    audio_bytes += chunk["data"]
            
            if not audio_bytes:
                raise Exception("No audio bytes generated by Edge-TTS")
                
            # Convert to base64 so the frontend can play it directly in <audio> tag
            base64_audio = base64.b64encode(audio_bytes).decode('utf-8')
            return f"data:audio/mp3;base64,{base64_audio}"
            
        except Exception as e:
            raise Exception(f"ApexSpeech generation failed: {str(e)}")
